#! /bin/sh
#
#by necronoise

PANEL_FIFO=/tmp/panel-fifo
PANEL_WM_NAME=bspwm_panel


COLOR_DEFAULT_FG="#3D4750"
#COLOR_DEFAULT_BG="#343c48"
COLOR_MONITOR_FG="#dee3e0"
#COLOR_MONITOR_BG="#343c48"
COLOR_FOCUSED_MONITOR_FG="#dee3e0"
#COLOR_FOCUSED_MONITOR_BG="#0A131A"
COLOR_FREE_FG="#3D4750"
COLOR_FREE_BG="#0A131A"
COLOR_FOCUSED_FREE_FG="#727D83"
COLOR_FOCUSED_FREE_BG="#0A131A"
COLOR_OCCUPIED_FG="#8D9EA8"
COLOR_OCCUPIED_BG="#0A131A"
COLOR_FOCUSED_OCCUPIED_FG="#AFC4DB"
COLOR_FOCUSED_OCCUPIED_BG="#0A131A"
COLOR_URGENT_FG="#dee3e0"
COLOR_URGENT_BG="#ba5e57"
COLOR_FOCUSED_URGENT_FG="#b48ead"
COLOR_FOCUSED_URGENT_BG="#ba5e57"
#COLOR_STATE_FG="#343c48"
#COLOR_STATE_BG="#343c48"
COLOR_SYS_FG="#AFC4DB"
COLOR_SYS_BG="#0A131A"
#COLOR_TITLE_FG="#859071"
#COLOR_TITLE_BG="#0A131A"

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

clock() {
    while true; do
        #date +"S$(icon  0) %H:%M"
	date +"S%b %d, %H:%M:%S"
        sleep 1
    done
}

volume() {
while true; do
	NOTMUTED=$(amixer -M | head -5 | grep "\[on\]")
	AUDIO=$(amixer -M | head -5 | grep -o -m 1 -E "[[:digit:]]+%")

	if [ -z "$NOTMUTED" ];
		then
			printf "%s\\n" "T Muted "
		else
			case "$AUDIO" in
				0%|[0-9]%) printf "%s\\n" "T $AUDIO " ;;
				1?%|2?%|3?%) printf "%s\\n" "T $AUDIO " ;;
				4?%|5?%|6?%) printf "%s\\n" "T $AUDIO " ;;
				*) printf "%s\\n" "T $AUDIO " ;;
			esac
	fi
	sleep 0.1
done
}

volume  > "$PANEL_FIFO" &
#xtitle -sf 'A%s\n' > "$PANEL_FIFO" &
#sys -sf 'S %a %b %d, %H:%M' > "$PANEL_FIFO" &
clock > "$PANEL_FIFO" & 
bspc subscribe report > "$PANEL_FIFO" &

num_mon=$(bspc query -M | wc -l)

bar_wm(){
while read -r line ; do
	case $line in
		T*)
			vol="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			sys="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
			;;
		A*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;

		W*)
			# workspaces output
			wm=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								on_focused_monitor=
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								on_focused_monitor=1
								;;
						esac
						[ $num_mon -lt 2 ] && shift && continue
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								UL=$BG
								;;
							F*)
								if [ "$on_focused_monitor" ] ; then
									# focused free desktop
									FG=$COLOR_FOCUSED_FREE_FG
									BG=$COLOR_FOCUSED_FREE_BG
									UL=$BG
								else
									# active free desktop
									FG=$COLOR_FREE_FG
									BG=$COLOR_FREE_BG
									UL=$COLOR_FOCUSED_FREE_BG
								fi
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								UL=$BG
								;;
							O*)
								if [ "$on_focused_monitor" ] ; then
									# focused occupied desktop
									FG=$COLOR_FOCUSED_OCCUPIED_FG
									BG=$COLOR_FOCUSED_OCCUPIED_BG
									UL=$BG
									else
									# active occupied desktop
									FG=$COLOR_OCCUPIED_FG
									BG=$COLOR_OCCUPIED_BG
									UL=$COLOR_FOCUSED_OCCUPIED_BG
								fi
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								UL=$BG
								;;
							U*)
								if [ "$on_focused_monitor" ] ; then
									# focused urgent desktop
									FG=$COLOR_FOCUSED_URGENT_FG
									BG=$COLOR_FOCUSED_URGENT_BG
									UL=$BG
								else
									# active urgent desktop
									FG=$COLOR_URGENT_FG
									BG=$COLOR_URGENT_BG
									UL=$COLOR_FOCUSED_URGENT_BG
								fi
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac


			printf "%s\n" "%{l}${wm}%{r}${vol}${sys}"
done
}


bar_wm < "$PANEL_FIFO" | lemonbar -a 30 -u 2 -n "$PANEL_WM_NAME" -g 1355x20+5+5 -f "gohufont:size=9" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
